# Site settings
title: Aaditya Ray 
subtitle: Homepage
tagline: Aaditya is a Techno-Functional Consultant, working for An American multinational consulting firm, at Liverpool street, London, United kingdom.
email: aadityaray@hotmail.com; 
email CC: aditya.r17@iimshillong.ac.in
description: Hi, I am interested in sports, music, family and friends. I am an MBA from IIM Shillong, and a B. Tech from Maulana Azad NIT Bhopal. I had previously worked for Hrasim Aditya birla group (as an Engineer) and Wipro (as Senior Consultant) at locations such as Bangalore(India), Baharain, Saudi Arabia and London (UK).   
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://soumyadeepdas.gitlab.io" # the base hostname & protocol for your site
logo: assets/images/favicon.png
image: assets/images/og-pic.jpg


# Blog posts
words_per_minute : 160
future : true
read_more : "disabled"

# projects
collections:
    projects:
        output: true

myversion: 4.5.0

author:
    name: Aaditya Ray
    avatar : assets/images/profile_picture.png
    avatar-webp: assets/images/profile_picture.webp
    avatar-thumb: assets/images/profile_picture-thumb.jpg
    # author-bio : "A NIT IIM boy-next-door Vlogger working at London."
    author-bio : "MBA in Finance, Strategy and  Marketing from IIM, B.Tech from NIT, A teenager State Topper back, working as Management Consultant in London and an Amateur Vlogger."
    ads : https://ui.adsabs.harvard.edu/
    facebook: https://www.facebook.com/aditya007ray
    github: https://github.com/aditya007ray
    gitlab: https://gitlab.com/aditya007ray
    googleplus: 
    googlescholar : https://mail.gmail.com/
    instagram: https://www.instagram.com/aditya007ray/
    linkedin: https://www.linkedin.com/in/aadityaray/
    orcid: https://orcid.org/
    pinterest:
    researchgate: https://www.researchgate.net
    slack:
    stackoverflow : https://stackoverflow.com/
    steam : https://steamcommunity.com/
    twitter: https://twitter.com/aditya007ray

# Social for SEO
twitter: 
  username: aditya007ray
  card: summary_large_image

facebook:
  app_id: 3425901884091023
  publisher: 3425901884091023   
  admins: 3425901884091023

social:
  name: Aaditya Ray
  links:
    - https://twitter.com/aditya007ray
    - https://www.instagram.com/aditya007ray
    - https://www.facebook.com/aditya007ray
    - https://github.com/aditya007ray
    - https://gitlab.com/aditya007ray
    - https://www.linkedin.com/in/aadityaray

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-gzip
  - jekyll-brotli
  - jekyll-redirect-from

# Build settings
markdown: kramdown



exclude:
  - vendor  
